AllCops:
  EnabledByDefault: true

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 120

Layout/IndentationConsistency:
  EnforcedStyle: rails
